apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gradeflower
  labels:
    name: gradeflower
    app: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gradeflower
    spec:
      containers:
        - name: gradeflower
          image: cs193s/tf-model-flower:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gradeflower
  labels:
    name: gradeflower
    app: front-end
spec:
  selector:
    name: gradeflower
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
