apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gradedr
  labels:
    name: gradedr
    app: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gradedr
    spec:
      containers:
        - name: gradedr
          image: tswedish/actdr:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gradedr
  labels:
    name: gradedr
    app: front-end
spec:
  selector:
    name: gradedr
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
