apiVersion: v1
kind: Pod
metadata:
  name: grade
  labels:
    name: grade
    app: front-end
spec:
  containers:
    - image: mmmarco/tf-model
      name: grade
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grade
  labels:
    name: grade
    app: front-end
spec:
  selector:
    name: grade
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
