apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: mongo
    app: front-end
spec:
  containers:
    - image: mongo:latest
      name: mongo
      ports:
      - name: mongo
        containerPort: 27017
        hostPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mongo
    app: front-end
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017
