apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grade
  labels:
    name: grade
    app: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grade
    spec:
      containers:
        - name: grade
          image: cs193s/tf-model:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grade
  labels:
    name: grade
    app: front-end
spec:
  selector:
    name: grade
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
