apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    app: front-end
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: mmmarco/api_server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: front-end
spec:
  selector:
    name: web
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
