apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: mongo
    app: front-end
spec:
  containers:
    - image: gcr.io/medical-image-grading-api/mongo:latest
      name: mongo
      ports:
      - name: mongo
        containerPort: 27017
        hostPort: 27017
