apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: front-end
spec:
  containers:
    - image: mmmarco/api_server:5.0
      name: myweb
      ports:
        - containerPort: 8080
