apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: front-end
spec:
  containers:
    - image: gcr.io/medical-image-grading-api/api_server:1.0
      name: myweb
      ports:
        - containerPort: 8080
