apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: front-end
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: mmmarco/api_server:5.0
        ports:
        - containerPort: 8080
